### ISSUE TITLE
Purge old requests

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/telos-oracle-rng#15]
## Overview
We want to remove the old requests, so they don't pile up. We want to add the functionality to purge requests according to their timestamp and the number of tries to call the callback.

## Acceptance Criteria
- Parameters that can be changed to define the timestamp and number of tries of the request that will be purged
- Keep track of the number of tries that the oracle tried to call the callback 
- Find requests that match both criteria and verify that they are successfully purged

**Comment by tomtomcrypto** [comment]
This has changed, we now delete requests on second notification of a callback failure by the oracle listeners.

**Comment by karynemayer** [comment]
@tomtomcrypto, does this mean that we're keeping all the successful requests, even the old ones? Could you provide more information on why we're not doing both constraints (timestamp and number of tries) as parameters?

**Comment by tomtomcrypto** [comment]
Yeah sorry, no successful requests are already deleted. We are not doing both constraint because as seen with Jesse timestamp doesn't matter at all.
